#!/usr/bin/env python3
"""Sole canonical writer: cm canonical upsert, generated catalog, tombstones, link rules."""
from __future__ import annotations

import os
import re
import sys
import time
from pathlib import Path
from typing import Optional

from domain_policy import admit_cross_project, fact_domain, fact_sensitivity, validate_write_policy
from index_admission import admit_write, project_index
from mirror_conflict import semantic_hash, stamp_revisions
from store_context import (StoreContext, WriteRefused, assert_writable, config_root,
                           warn_unenrolled_share)

_SAFE_NAME = re.compile(r"^[A-Za-z0-9._-]+$")
_LINK_RE = re.compile(r"\[\[([^\]]+)\]\]")
SCOPE_RANK = {"project-local": 0, "stack-general": 1, "user-global": 2}


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + f".tmp{os.getpid()}")
    try:
        tmp.write_text(text, encoding="utf-8")
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def generate_catalog(facts_dir: Path, overlay: Optional[dict] = None) -> str:
    """Generated global MEMORY.md — not hand-maintained source of truth.

    `overlay` maps filename → body for staged temps not yet on disk.
    """
    lines = ["# Memory Index", "", "<!-- generated by cm canonical upsert; do not hand-edit -->", ""]
    overlay = overlay or {}
    stems: dict = {}
    if facts_dir.is_dir():
        for f in sorted(facts_dir.glob("*.md")):
            if f.name == "MEMORY.md":
                continue
            try:
                stems[f.stem] = f.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
    for name, text in overlay.items():
        stem = Path(name).stem if "/" in name or name.endswith(".md") else name
        if stem == "MEMORY":
            continue
        stems[stem] = text
    for stem in sorted(stems):
        text = stems[stem]
        if not text:
            continue
        status = ""
        desc = ""
        for ln in text.splitlines():
            s = ln.strip()
            if s.startswith("status:"):
                status = s.split(":", 1)[1].strip()
            elif s.startswith("description:"):
                desc = s.split(":", 1)[1].strip()
        if status == "tombstoned":
            continue
        lines.append(f"- [{stem}]({stem}.md) — {desc}".rstrip(" —"))
    return "\n".join(lines) + "\n"


_MIRROR_KEYS = (
    "global_ref:", "global_ref_since:", "global_ref_body:",
    "base_revision:", "canonical_revision:", "mirrored_at:",
)


def demirror_text(text: str) -> str:
    """Strip managed-mirror markup so a local edit can become a canonical body.

    Frontmatter-scoped (same fence rule as `_as_mirror`). Pure.
    """
    if not text.startswith("---"):
        return text
    out: list = []
    dashes = 0
    for i, ln in enumerate(text.splitlines()):
        s = ln.strip()
        if dashes == 0:
            if i == 0 and ln == "---":
                dashes = 1
                out.append(ln)
            else:
                out.append(ln)
            continue
        if dashes == 1 and ln.startswith("---"):
            dashes = 2
            out.append(ln)
            continue
        if dashes == 1 and s.startswith(_MIRROR_KEYS):
            continue
        out.append(ln)
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")


def insert_frontmatter_key(text: str, key: str, value: str) -> str:
    """Set `key: value` in the opening frontmatter; preserve unknown keys. Pure."""
    k = (key or "").strip()
    if not k:
        return text
    line = f"{k}: {value}"
    if not text.startswith("---"):
        body = text if text.endswith("\n") or not text else text + "\n"
        return f"---\n{line}\n---\n\n{body}"
    out: list = []
    dashes = 0
    seen = False
    for i, ln in enumerate(text.splitlines()):
        s = ln.strip()
        if dashes == 0 and i == 0 and ln == "---":
            dashes = 1
            out.append(ln)
            continue
        if dashes == 1 and ln.startswith("---"):
            if not seen:
                out.append(line)
            dashes = 2
            out.append(ln)
            continue
        if dashes == 1 and s.startswith(k + ":"):
            out.append(line)
            seen = True
            continue
        out.append(ln)
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")


def link_targets(text: str) -> list:
    return [m for m in _LINK_RE.findall(text) if "." not in m]


def link_allowed(src_scope: str, dst_scope: str, *, dst_exists_global: bool = False,
                 dst_external: bool = False) -> bool:
    """Monotone dependencies. Wider must not require narrower."""
    if dst_external:
        return True
    src = SCOPE_RANK.get(src_scope, 0)
    dst = SCOPE_RANK.get(dst_scope, 0)
    if src > dst:
        return False  # wider → narrower
    if src_scope == "user-global" and dst_scope not in ("user-global",) and not dst_external:
        return False
    return True


def validate_links(text: str, src_scope: str, facts_dir: Path,
                   scope_of: Optional[dict] = None) -> Optional[str]:
    scopes = scope_of or {}
    for target in link_targets(text):
        dest = facts_dir / f"{target}.md"
        if dest.exists():
            dst_scope = scopes.get(target) or _scope_of(dest)
            if not link_allowed(src_scope, dst_scope, dst_exists_global=True):
                return f"invalid link [[{target}]]: {src_scope} must not require {dst_scope}"
            continue
        # not a canonical — project-local or missing. Wider facts cannot require it.
        if src_scope in ("user-global", "stack-general"):
            return f"invalid link [[{target}]]: {src_scope} must not require a non-canonical target"
    return None


def _scope_of(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "project-local"
    for ln in text.splitlines():
        s = ln.strip()
        if s.startswith("scope:"):
            return s.split(":", 1)[1].strip()
    return "project-local"


def _looks_secret_fn():
    from memory_status import _looks_secret
    return _looks_secret


def _with_timestamps(text: str, now: str, *, body_changed: bool = True) -> str:
    """Preserve unknown frontmatter; add content_modified / last_observed_at.

    Metadata-only restamps keep content_modified (ADR 011).
    """
    if not text.startswith("---"):
        return text
    lines = text.splitlines()
    out = []
    dashes = 0
    seen = set()
    for i, ln in enumerate(lines):
        s = ln.strip()
        if dashes == 0 and i == 0 and ln == "---":
            dashes = 1
            out.append(ln)
            continue
        if dashes == 1 and ln.startswith("---"):
            if "content_modified" not in seen and body_changed:
                out.append(f"content_modified: {now}")
            if "last_observed_at" not in seen:
                out.append(f"last_observed_at: {now}")
            dashes = 2
            out.append(ln)
            continue
        if dashes == 1 and s.startswith("content_modified:"):
            out.append(f"content_modified: {now}" if body_changed else ln)
            seen.add("content_modified")
            continue
        if dashes == 1 and s.startswith("last_observed_at:"):
            out.append(f"last_observed_at: {now}")
            seen.add("last_observed_at")
            continue
        out.append(ln)
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")


def prepare_migrated_canonical(text: str, *, stem: str, domain: str) -> tuple:
    """Same inject + validate path upsert uses, without requiring scope.

    Missing scope stays not-pullable until assigned (ADR 008 / Step 5).
    Returns (body, error).
    """
    from control_plane import stable_fact_id
    from fact_schema import validate_canonical_frontmatter
    from memory_status import _frontmatter
    body = text if text.endswith("\n") else text + "\n"
    body = insert_frontmatter_key(body, "name", stem)
    body = insert_frontmatter_key(body, "domain", domain)
    body = insert_frontmatter_key(body, "schema_version", "3")
    body = insert_frontmatter_key(body, "fact_id", stable_fact_id(domain, stem))
    fm = _frontmatter(body)
    if not str(fm.get("sensitivity") or "").strip():
        body = insert_frontmatter_key(body, "sensitivity", "internal")
    if not str(fm.get("status") or "").strip():
        body = insert_frontmatter_key(body, "status", "active")
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    body = _with_timestamps(body if body.endswith("\n") else body + "\n", now,
                            body_changed=True)
    fm = _frontmatter(body)
    err = validate_canonical_frontmatter(fm, stem=stem, domain=domain)
    return body, err


def upsert(ctx: StoreContext, stem: str, text: str, *,
           origin_local: Optional[Path] = None,
           origin_delete: Optional[Path] = None,
           crash_after: Optional[str] = None,
           skip_recover: bool = False,
           create_only: bool = False,
           preserve_canonical: bool = False) -> dict:
    """Sole path that creates/updates a canonical. Transactional.

    `origin_local` may not exist yet (promote rename: write the origin mirror at the
    new stem). `preserve_canonical` is the reconcile path: never overwrite an existing
    canonical body; still record the holder and convert the origin.
    """
    from control_plane import (CrashSimulated, is_tombstoned, record_holder,
                               stable_fact_id, transact)
    from memory_status import _frontmatter

    from identifiers import IdentifierRefused, validate_fact_stem
    try:
        stem = validate_fact_stem(stem or "")
    except IdentifierRefused:
        return {"ok": False, "error": "unsafe or reserved stem"}
    assert_writable(ctx)
    warn_unenrolled_share(ctx)
    if not getattr(ctx, "cross_project_allowed", False):
        return {"ok": False, "error":
                "cross-project writes require enrollment into a named domain "
                "(cm project enroll --domain NAME)"}
    text = insert_frontmatter_key(text if text.endswith("\n") else text + "\n", "name", stem)
    if ctx.domain_id and ctx.domain_id != "unknown":
        text = insert_frontmatter_key(text, "domain", ctx.domain_id)
    text = insert_frontmatter_key(text, "schema_version", "3")
    _fid_up = stable_fact_id(ctx.domain_id, stem)
    text = insert_frontmatter_key(text, "fact_id", _fid_up)
    fm = _frontmatter(text)
    if not str(fm.get("sensitivity") or "").strip():
        text = insert_frontmatter_key(text, "sensitivity", "internal")
    if not str(fm.get("status") or "").strip():
        text = insert_frontmatter_key(text, "status", "active")
    fm = _frontmatter(text)
    if not str(fm.get("scope") or "").strip():
        return {"ok": False, "error":
                "scope is required (project-local|stack-general|user-global)"}
    from fact_schema import validate_canonical_frontmatter
    schema_err = validate_canonical_frontmatter(fm, stem=stem, domain=ctx.domain_id)
    if schema_err:
        return {"ok": False, "error": schema_err}
    err = validate_write_policy(text, fm, looks_secret=_looks_secret_fn(), domain=ctx.domain_id)
    if err:
        return {"ok": False, "error": err}
    scope = str(fm.get("scope") or "user-global")
    link_err = validate_links(text, scope, ctx.canonical_domain_dir)
    if link_err:
        return {"ok": False, "error": link_err}
    if ctx.domain_id == "unknown" and fact_domain(fm):
        return {"ok": False, "error": "unknown-domain writer cannot create a domain-tagged canonical"}

    facts_dir = ctx.canonical_domain_dir
    from sync_global import global_store as _gstore, _body as _body_up
    legacy = _gstore()
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    dest_existing = facts_dir / f"{stem}.md"
    prev_text = dest_existing.read_text(encoding="utf-8", errors="replace") if dest_existing.exists() else ""
    body_changed = (not prev_text) or (_body_up(prev_text) != _body_up(text))
    body = _with_timestamps(text if text.endswith("\n") else text + "\n", now,
                            body_changed=body_changed)

    def mutate(conn, temps):
        from index_admission import apply_pointer, project_index
        from sync_global import (_as_mirror, _body_hash, _fat_hook_warning,
                                 _pointer_line, apply_provenance)
        if is_tombstoned(conn, stem, ctx.domain_id or "unknown"):
            raise WriteRefused(f"tombstoned: {stem} (will not resurrect)")
        dest = facts_dir / f"{stem}.md"
        try:
            same_dir = dest.resolve().parent == legacy.resolve()
        except OSError:
            same_dir = dest.parent == legacy
        if create_only and dest.exists():
            raise WriteRefused(
                "canonical already exists (created concurrently); retry to reconcile")
        deletes: list = []
        if preserve_canonical:
            live = dest if dest.exists() else (legacy / f"{stem}.md")
            if not live.exists():
                raise WriteRefused("preserve_canonical but canonical missing")
            existing_body = live.read_text(encoding="utf-8", errors="replace")
            provenanced = apply_provenance(existing_body, ctx.display_name)
            if provenanced != existing_body:
                temps[str(dest)] = provenanced
            canon_body = provenanced
        else:
            provenanced = apply_provenance(body, ctx.display_name)
            catalog = generate_catalog(facts_dir, overlay={stem: provenanced})
            pointer = f"- [{stem}]({stem}.md) — {str(fm.get('description') or stem)}"
            future = apply_pointer(catalog, pointer, stem)
            # Native 200-line/25KB caps apply only to a project's MEMORY.md.
            # Legacy <config>/memory is a read-only migration source (P0-3).
            temps[str(dest)] = provenanced
            temps[str(facts_dir / "MEMORY.md")] = future
            canon_body = provenanced
        rev = semantic_hash(canon_body)
        fid = stable_fact_id(ctx.domain_id, stem)
        conn.execute(
            "INSERT INTO facts(fact_id, stem, domain_id, canonical_path, revision, status, sensitivity) "
            "VALUES (?,?,?,?,?,?,?) ON CONFLICT(fact_id) DO UPDATE SET revision=excluded.revision, "
            "canonical_path=excluded.canonical_path, status='active', sensitivity=excluded.sensitivity",
            (fid, stem, ctx.domain_id, str(dest), rev, "active", fact_sensitivity(fm)),
        )
        record_holder(conn, fid, ctx.project_id, rev, rev, rev)
        if origin_local is not None:
            bh = _body_hash(canon_body)
            mirror = _as_mirror(canon_body, stem, since=now, body_hash=bh,
                                fact_id=fid, domain=ctx.domain_id)
            mirror = stamp_revisions(mirror, rev, rev)
            if "mirrored_at:" not in mirror and "  global_ref:" in mirror:
                mirror = mirror.replace(
                    "  global_ref:", f"  mirrored_at: {now}\n  global_ref:", 1)
            if "mirrored_at:" not in mirror:
                mirror = mirror.replace("---\n", f"---\nmirrored_at: {now}\n", 1)
            temps[str(origin_local)] = mirror
            idxp = origin_local.parent / "MEMORY.md"
            idx_text = idxp.read_text(encoding="utf-8", errors="replace") if idxp.exists() else (
                "# Memory Index\n\n")
            if origin_delete is not None:
                old = origin_delete.stem
                idx_text = "\n".join(
                    ln for ln in idx_text.splitlines() if f"]({old}.md)" not in ln
                ) + "\n"
            ptr = _pointer_line(stem, _frontmatter(canon_body))
            lint = _fat_hook_warning(ptr, stem)
            future_idx = apply_pointer(idx_text, ptr, stem)
            adm = project_index(future_idx)
            if not adm["admitted"]:
                raise WriteRefused(
                    "index admission refused; origin not converted or deleted: "
                    + adm["reason"])
            temps[str(idxp)] = future_idx if future_idx.endswith("\n") else future_idx + "\n"
            if lint:
                print(f"  {lint}", file=sys.stderr)
            if origin_delete is not None:
                try:
                    same_origin = origin_local.resolve() == origin_delete.resolve()
                except OSError:
                    same_origin = origin_local == origin_delete
                if not same_origin:
                    deletes.append(str(origin_delete))
        modes = {}
        if create_only:
            modes[str(dest)] = "create"
        return {
            "stem": stem, "fact_id": fid, "revision": rev, "catalog_admitted": True,
            "deletes": deletes,
            "holders": [(fid, ctx.project_id, rev, rev, rev)],
            "facts": [(fid, stem, ctx.domain_id, str(dest), rev, "active",
                       fact_sensitivity(fm))],
            "dest_modes": modes,
            "registry_ops": [
                {"op": "fact_upsert", "fact_id": fid, "stem": stem,
                 "domain_id": ctx.domain_id, "canonical_path": str(dest),
                 "revision": rev, "status": "active",
                 "sensitivity": fact_sensitivity(fm)},
                {"op": "holder_upsert", "fact_id": fid, "project_id": ctx.project_id,
                 "base_revision": rev, "canonical_revision": rev, "semantic_hash": rev},
            ],
        }

    payload = {"stem": stem, "text": text,
               "origin": str(origin_local) if origin_local else "",
               "origin_delete": str(origin_delete) if origin_delete else "",
               "preserve_canonical": bool(preserve_canonical),
               "create_only": bool(create_only)}
    expected = {}
    from control_plane import ABSENT as _ABS, _file_hash as _fh_up
    dest_p = facts_dir / f"{stem}.md"
    if dest_p.exists():
        h = _fh_up(dest_p)
        if h:
            expected[str(dest_p)] = h
    elif create_only:
        expected[str(dest_p)] = _ABS
    if origin_local is not None and origin_local.exists():
        h = _fh_up(origin_local)
        if h:
            expected[str(origin_local)] = h
    try:
        out = transact(ctx, "canonical-upsert", payload, mutate,
                       crash_after=crash_after, skip_recover=skip_recover,
                       expected_revisions=expected or None)
        return {"ok": True, **(out.get("result") or {}), "op_id": out.get("op_id")}
    except WriteRefused as e:
        return {"ok": False, "error": str(e)}
    except CrashSimulated as e:
        return {"ok": False, "error": f"crash-after:{e}", "crashed": str(e)}


def forget(ctx: StoreContext, stem: str, reason: str = "user-forget",
           replacement_id: str = "", grace_until: str = "") -> dict:
    from identifiers import IdentifierRefused, validate_fact_stem
    from control_plane import stable_fact_id, transact, write_tombstone
    try:
        stem = validate_fact_stem(stem)
    except IdentifierRefused as e:
        return {"ok": False, "error": str(e)}
    warn_unenrolled_share(ctx)
    if not getattr(ctx, "cross_project_allowed", False):
        return {"ok": False, "error":
                "cross-project writes require enrollment into a named domain "
                "(cm project enroll --domain NAME)"}

    def mutate(conn, temps):
        fid = stable_fact_id(ctx.domain_id, stem)
        write_tombstone(conn, fid, stem, ctx.domain_id, reason, replacement_id, grace_until)
        p = ctx.canonical_domain_dir / f"{stem}.md"
        prev = ""
        if p.exists():
            prev = p.read_text(encoding="utf-8", errors="replace")
        temps[str(p)] = _tombstone_markdown(stem, reason, replacement_id, grace_until, prev)
        # Overlay: generate_catalog still reads the live file on disk; strip this
        # stem's pointer so the catalog published in the same transact omits it.
        cat = generate_catalog(ctx.canonical_domain_dir)
        lines = [ln for ln in cat.splitlines() if f"]({stem}.md)" not in ln]
        temps[str(ctx.canonical_domain_dir / "MEMORY.md")] = "\n".join(lines) + "\n"
        deletes: list = []
        dest_modes: dict = {}
        origin = ctx.native_memory_dir / f"{stem}.md"
        from sync_global import _is_mirror, _safe_read_text as _srt_fg
        from mirror_conflict import classify_mirror as _cm_fg
        from control_plane import holder_base_revision as _hbr_fg
        ot = _srt_fg(origin)
        hb = _hbr_fg(conn, fid, ctx.project_id)
        conn.execute("DELETE FROM holders WHERE fact_id=? AND project_id=?",
                     (fid, ctx.project_id))
        if ot is not None and _is_mirror(ot):
            idxp = ctx.native_memory_dir / "MEMORY.md"
            idx = _srt_fg(idxp) or ""
            idx = "\n".join(ln for ln in idx.splitlines() if f"]({stem}.md)" not in ln)
            temps[str(idxp)] = idx.rstrip() + "\n"
            if not prev:
                dec = {"action": "quarantine"}
            else:
                dec = _cm_fg(ot, prev, base_revision=hb, allow_legacy_fallback=False)
            if dec["action"] in ("stop-local", "conflict", "quarantine"):
                qdir = ctx.native_memory_dir / "quarantine"
                qdir.mkdir(parents=True, exist_ok=True)
                ts = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
                qdest = qdir / f"{stem}.{ts}.md"
                n = 0
                while qdest.exists() or str(qdest) in temps:
                    n += 1
                    qdest = qdir / f"{stem}.{ts}.{n}.md"
                temps[str(qdest)] = ot if ot.endswith("\n") else ot + "\n"
                dest_modes[str(qdest)] = "create"
                deletes.append(str(origin))
            else:
                deletes.append(str(origin))
        return {"stem": stem, "tombstoned": True, "deletes": deletes,
                "tombstones": [(fid, stem, ctx.domain_id, reason, replacement_id, grace_until)],
                "dest_modes": dest_modes,
                "registry_ops": [
                    {"op": "tombstone_upsert", "fact_id": fid, "stem": stem,
                     "domain_id": ctx.domain_id, "reason": reason,
                     "replacement_id": replacement_id, "grace_until": grace_until},
                    {"op": "holder_delete", "fact_id": fid, "project_id": ctx.project_id},
                ]}

    try:
        out = transact(ctx, "forget", {"stem": stem, "reason": reason}, mutate)
        return {"ok": True, **(out.get("result") or {})}
    except WriteRefused as e:
        return {"ok": False, "error": str(e)}


def _tombstone_markdown(stem: str, reason: str, replacement_id: str,
                        grace_until: str, previous: str) -> str:
    import hashlib
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    def _esc(s: str) -> str:
        return str(s or "").replace("\n", " ").replace("\r", " ")[:200]

    rev = hashlib.sha256((previous or "").encode("utf-8")).hexdigest()[:16]
    return (
        f"---\nname: {stem}\nstatus: tombstoned\ndeleted_at: {now}\n"
        f"reason: {_esc(reason)}\nreplacement_id: {_esc(replacement_id)}\n"
        f"grace_until: {_esc(grace_until)}\ndeleted_revision_hash: {rev}\n---\n\n"
        f"Tombstone. Previous body is not retained.\n"
    )


def hand_edit_refused_or_regenerated(facts_dir: Path) -> str:
    """Any hand-edited catalog is overwritten by generation."""
    catalog = generate_catalog(facts_dir)
    _atomic_write(facts_dir / "MEMORY.md", catalog)
    return catalog
