#!/usr/bin/env python3
"""Sole canonical writer: cm canonical upsert, generated catalog, tombstones, link rules."""
from __future__ import annotations

import os
import re
import time
from pathlib import Path
from typing import Optional

from domain_policy import admit_cross_project, fact_domain, fact_sensitivity, validate_write_policy
from index_admission import admit_write, project_index
from mirror_conflict import semantic_hash, stamp_revisions
from store_context import StoreContext, WriteRefused, assert_writable, config_root

_SAFE_NAME = re.compile(r"^[A-Za-z0-9._-]+$")
_LINK_RE = re.compile(r"\[\[([^\]]+)\]\]")
SCOPE_RANK = {"project-local": 0, "stack-general": 1, "user-global": 2}


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + f".tmp{os.getpid()}")
    try:
        tmp.write_text(text, encoding="utf-8")
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def generate_catalog(facts_dir: Path) -> str:
    """Generated global MEMORY.md — not hand-maintained source of truth."""
    lines = ["# Memory Index", "", "<!-- generated by cm canonical upsert; do not hand-edit -->", ""]
    if not facts_dir.is_dir():
        return "\n".join(lines) + "\n"
    for f in sorted(facts_dir.glob("*.md")):
        if f.name == "MEMORY.md":
            continue
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        desc = ""
        for ln in text.splitlines():
            if ln.strip().startswith("description:"):
                desc = ln.split(":", 1)[1].strip()
                break
        lines.append(f"- [{f.stem}]({f.name}) — {desc}".rstrip(" —"))
    return "\n".join(lines) + "\n"


def link_targets(text: str) -> list:
    return [m for m in _LINK_RE.findall(text) if "." not in m]


def link_allowed(src_scope: str, dst_scope: str, *, dst_exists_global: bool = False,
                 dst_external: bool = False) -> bool:
    """Monotone dependencies. Wider must not require narrower."""
    if dst_external:
        return True
    src = SCOPE_RANK.get(src_scope, 0)
    dst = SCOPE_RANK.get(dst_scope, 0)
    if src > dst:
        return False  # wider → narrower
    if src_scope == "user-global" and dst_scope not in ("user-global",) and not dst_external:
        return False
    return True


def validate_links(text: str, src_scope: str, facts_dir: Path,
                   scope_of: Optional[dict] = None) -> Optional[str]:
    scopes = scope_of or {}
    for target in link_targets(text):
        dest = facts_dir / f"{target}.md"
        if dest.exists():
            dst_scope = scopes.get(target) or _scope_of(dest)
            if not link_allowed(src_scope, dst_scope, dst_exists_global=True):
                return f"invalid link [[{target}]]: {src_scope} must not require {dst_scope}"
            continue
        # not a canonical — project-local or missing. Wider facts cannot require it.
        if src_scope in ("user-global", "stack-general"):
            return f"invalid link [[{target}]]: {src_scope} must not require a non-canonical target"
    return None


def _scope_of(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "project-local"
    for ln in text.splitlines():
        s = ln.strip()
        if s.startswith("scope:"):
            return s.split(":", 1)[1].strip()
    return "project-local"


def _looks_secret_fn():
    from memory_status import _looks_secret
    return _looks_secret


def _with_timestamps(text: str, now: str) -> str:
    """Preserve unknown frontmatter; add content_modified / last_observed_at."""
    if not text.startswith("---"):
        return text
    lines = text.splitlines()
    out = []
    dashes = 0
    seen = set()
    for i, ln in enumerate(lines):
        s = ln.strip()
        if dashes == 0 and i == 0 and ln == "---":
            dashes = 1
            out.append(ln)
            continue
        if dashes == 1 and ln.startswith("---"):
            if "content_modified" not in seen:
                out.append(f"content_modified: {now}")
            if "last_observed_at" not in seen:
                out.append(f"last_observed_at: {now}")
            dashes = 2
            out.append(ln)
            continue
        if dashes == 1 and s.startswith("content_modified:"):
            out.append(f"content_modified: {now}")
            seen.add("content_modified")
            continue
        if dashes == 1 and s.startswith("last_observed_at:"):
            out.append(f"last_observed_at: {now}")
            seen.add("last_observed_at")
            continue
        out.append(ln)
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")


def upsert(ctx: StoreContext, stem: str, text: str, *,
           origin_local: Optional[Path] = None,
           origin_delete: Optional[Path] = None,
           crash_after: Optional[str] = None,
           skip_recover: bool = False,
           create_only: bool = False,
           preserve_canonical: bool = False) -> dict:
    """Sole path that creates/updates a canonical. Transactional.

    `origin_local` may not exist yet (promote rename: write the origin mirror at the
    new stem). `preserve_canonical` is the reconcile path: never overwrite an existing
    canonical body; still record the holder and convert the origin.
    """
    from control_plane import (CrashSimulated, is_tombstoned, record_holder,
                               stable_fact_id, transact)
    from memory_status import _frontmatter

    if not _SAFE_NAME.fullmatch(stem or "") or stem.upper() == "MEMORY":
        return {"ok": False, "error": "unsafe or reserved stem"}
    assert_writable(ctx)
    fm = _frontmatter(text)
    err = validate_write_policy(text, fm, looks_secret=_looks_secret_fn(), domain=ctx.domain_id)
    if err:
        return {"ok": False, "error": err}
    scope = str(fm.get("scope") or "user-global")
    link_err = validate_links(text, scope, ctx.canonical_domain_dir)
    if link_err:
        return {"ok": False, "error": link_err}
    if ctx.domain_id == "unknown" and fact_domain(fm):
        return {"ok": False, "error": "unknown-domain writer cannot create a domain-tagged canonical"}

    facts_dir = ctx.canonical_domain_dir
    from sync_global import global_store as _gstore
    legacy = _gstore()
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    body = _with_timestamps(text if text.endswith("\n") else text + "\n", now)

    def mutate(conn, temps):
        from index_admission import apply_pointer, project_index
        from sync_global import (_as_mirror, _body_hash, _fat_hook_warning,
                                 _pointer_line, apply_provenance)
        if is_tombstoned(conn, stem, ctx.domain_id if ctx.domain_id != "unknown" else ""):
            raise WriteRefused(f"tombstoned: {stem} (will not resurrect)")
        dest = facts_dir / f"{stem}.md"
        try:
            same_dir = dest.resolve().parent == legacy.resolve()
        except OSError:
            same_dir = dest.parent == legacy
        if create_only and (dest.exists() or (legacy / f"{stem}.md").exists()):
            raise WriteRefused(
                "canonical already exists (created concurrently); retry to reconcile")
        deletes: list = []
        if preserve_canonical:
            live = dest if dest.exists() else (legacy / f"{stem}.md")
            if not live.exists():
                raise WriteRefused("preserve_canonical but canonical missing")
            existing_body = live.read_text(encoding="utf-8", errors="replace")
            provenanced = apply_provenance(existing_body, ctx.display_name)
            if provenanced != existing_body:
                temps[str(dest)] = provenanced
                if not same_dir:
                    temps[str(legacy / f"{stem}.md")] = provenanced
            canon_body = provenanced
        else:
            provenanced = apply_provenance(body, ctx.display_name)
            catalog = generate_catalog(facts_dir)
            pointer = f"- [{stem}]({stem}.md) — {str(fm.get('description') or stem)}"
            future = apply_pointer(catalog, pointer, stem)
            decision = project_index(future)
            if not decision["admitted"]:
                raise WriteRefused("index admission refused: " + decision["reason"])
            temps[str(dest)] = provenanced
            temps[str(facts_dir / "MEMORY.md")] = future
            if not same_dir:
                temps[str(legacy / f"{stem}.md")] = provenanced
                temps[str(legacy / "MEMORY.md")] = apply_pointer(
                    generate_catalog(legacy), pointer, stem)
            canon_body = provenanced
        rev = semantic_hash(canon_body)
        fid = stable_fact_id(ctx.domain_id, stem)
        conn.execute(
            "INSERT INTO facts(fact_id, stem, domain_id, canonical_path, revision, status, sensitivity) "
            "VALUES (?,?,?,?,?,?,?) ON CONFLICT(fact_id) DO UPDATE SET revision=excluded.revision, "
            "canonical_path=excluded.canonical_path, status='active', sensitivity=excluded.sensitivity",
            (fid, stem, ctx.domain_id, str(dest), rev, "active", fact_sensitivity(fm)),
        )
        record_holder(conn, fid, ctx.project_id, rev, rev, rev)
        if origin_local is not None:
            bh = _body_hash(canon_body)
            mirror = _as_mirror(canon_body, stem, since=now, body_hash=bh)
            mirror = stamp_revisions(mirror, rev, rev)
            if "mirrored_at:" not in mirror and "  global_ref:" in mirror:
                mirror = mirror.replace(
                    "  global_ref:", f"  mirrored_at: {now}\n  global_ref:", 1)
            if "mirrored_at:" not in mirror:
                mirror = mirror.replace("---\n", f"---\nmirrored_at: {now}\n", 1)
            temps[str(origin_local)] = mirror
            idxp = origin_local.parent / "MEMORY.md"
            idx_text = idxp.read_text(encoding="utf-8", errors="replace") if idxp.exists() else (
                "# Memory Index\n\n")
            if origin_delete is not None:
                old = origin_delete.stem
                idx_text = "\n".join(
                    ln for ln in idx_text.splitlines() if f"]({old}.md)" not in ln
                ) + "\n"
            ptr = _pointer_line(stem, _frontmatter(canon_body))
            lint = _fat_hook_warning(ptr, stem)
            future_idx = apply_pointer(idx_text, ptr, stem)
            adm = project_index(future_idx)
            if adm["admitted"]:
                temps[str(idxp)] = future_idx if future_idx.endswith("\n") else future_idx + "\n"
                if lint:
                    print(f"  {lint}", file=sys.stderr)
            else:
                print(f"  ⚠ index admission refused for '{stem}': {adm['reason']}",
                      file=sys.stderr)
            if origin_delete is not None:
                try:
                    same_origin = origin_local.resolve() == origin_delete.resolve()
                except OSError:
                    same_origin = origin_local == origin_delete
                if not same_origin:
                    deletes.append(str(origin_delete))
        return {"stem": stem, "fact_id": fid, "revision": rev, "catalog_admitted": True,
                "deletes": deletes}

    payload = {"stem": stem, "text": text,
               "origin": str(origin_local) if origin_local else "",
               "origin_delete": str(origin_delete) if origin_delete else "",
               "preserve_canonical": bool(preserve_canonical),
               "create_only": bool(create_only)}
    try:
        out = transact(ctx, "canonical-upsert", payload, mutate,
                       crash_after=crash_after, skip_recover=skip_recover)
        return {"ok": True, **(out.get("result") or {}), "op_id": out.get("op_id")}
    except WriteRefused as e:
        return {"ok": False, "error": str(e)}
    except CrashSimulated as e:
        return {"ok": False, "error": f"crash-after:{e}", "crashed": str(e)}


def forget(ctx: StoreContext, stem: str, reason: str = "user-forget",
           replacement_id: str = "", grace_until: str = "") -> dict:
    from control_plane import stable_fact_id, transact, write_tombstone
    from sync_global import global_store as _gstore

    def mutate(conn, temps):
        fid = stable_fact_id(ctx.domain_id, stem)
        write_tombstone(conn, fid, stem, ctx.domain_id, reason, replacement_id, grace_until)
        seen = set()
        for base in (ctx.canonical_domain_dir, ctx.config_root / "memory", _gstore()):
            p = base / f"{stem}.md"
            try:
                key = str(p.resolve())
            except OSError:
                key = str(p)
            if key in seen:
                continue
            seen.add(key)
            if p.exists():
                prev = p.read_text(encoding="utf-8", errors="replace")
                temps[str(p)] = _tombstone_markdown(stem, reason, replacement_id, grace_until, prev)
        return {"stem": stem, "tombstoned": True}

    try:
        out = transact(ctx, "forget", {"stem": stem, "reason": reason}, mutate)
        return {"ok": True, **(out.get("result") or {})}
    except WriteRefused as e:
        return {"ok": False, "error": str(e)}


def _tombstone_markdown(stem: str, reason: str, replacement_id: str,
                        grace_until: str, previous: str) -> str:
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    return (
        f"---\nname: {stem}\nstatus: tombstoned\ndeleted_at: {now}\n"
        f"reason: {reason}\nreplacement_id: {replacement_id}\ngrace_until: {grace_until}\n---\n\n"
        f"Tombstone. Previous body retained below the cut for recovery.\n\n"
        f"<!-- previous\n{previous}\n-->\n"
    )


def hand_edit_refused_or_regenerated(facts_dir: Path) -> str:
    """Any hand-edited catalog is overwritten by generation."""
    catalog = generate_catalog(facts_dir)
    _atomic_write(facts_dir / "MEMORY.md", catalog)
    return catalog
