#!/usr/bin/env bash
# MAINTAINER continuous-QA gate for the consolidate-memory "dream" skill.
#
# For the marketplace owner who DEVELOPS consolidate-memory. Installed as a pre-push hook by
# `install-gate.sh`, it runs the deterministic beta-oracle against the version being pushed (the
# repo's working tree) on a FROZEN fixture and BLOCKS (exit 1) on any confirmed FAIL. End users who
# merely INSTALL the plugin don't need this — they use the `/dream-beta-test` skill.
#
# SELF-TEST (watch-the-watcher): proves the oracle still detects a frozen known-bad before trusting
# an "allow". FAIL-OPEN on any harness malfunction. Override a block with `git push --no-verify`.
# Writes the deterministic orchestrator contract to $REPORTS/latest.json (see ../docs/CONTRACT.md).
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SCRIPTS="$(cd "$HERE/../scripts" && pwd)"                       # plugin-relative engine
STATE="${DREAM_BETA_STATE:-$HOME/.dream-beta-test}"            # stable maintainer state (fixture/canary/reports)
REPORTS="${DREAM_BETA_REPORTS:-$STATE/reports}"
TEST_REPO="$STATE/gate-repo"                                    # generated by install-gate.sh / make_fixture.py
CANARY="${DBT_GATE_CANARY:-$STATE/canary-v0.1.19/scripts}"     # frozen known-bad (install-gate.sh populates it)
PROBE_FILE="$STATE/cycle-probe.json"                           # v0.1.8/A1: frozen contaminated record (install-gate.sh generates it)
# The consolidate-memory scripts being pushed = the working tree of the repo the hook fires in.
SKILL="${DBT_GATE_SKILL:-$(git rev-parse --show-toplevel 2>/dev/null)/plugins/consolidate-memory/scripts}"
TAG="[dream-beta-test gate]"
now() { date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo now; }
ver() { python3 -c "import json;print(json.load(open('$SKILL/../.claude-plugin/plugin.json'))['version'])" 2>/dev/null || echo "?"; }

# Setup / sanity — any miss → FAIL-OPEN (a beta-tester must not block work on its own gaps).
if [ ! -f "$SCRIPTS/beta_checks.py" ] || [ ! -f "$SKILL/memory_status.py" ]; then
  echo "$TAG engine or consolidate-memory scripts not found — gate SKIPPED (fail-open)." >&2; exit 0; fi
if [ ! -f "$TEST_REPO/README.md" ]; then
  echo "$TAG fixture not set up — run $HERE/install-gate.sh first. Gate SKIPPED (fail-open)." >&2; exit 0; fi

# v0.1.8/A6 SELF-HEAL: the fixture's trigger-node mirror is an ORPHAN by construction (its
# canonical is deliberately fictional) — the maintainer's own `sync_global --gc --apply` reclaims
# it, un-making the node until CHK-CYCLE-BUDGET silently vanishes from the run (→ probe
# teeth-loss). Regenerate the idempotent fixture when the mirror is missing, and say so loudly.
_FIX_SLUG="$(python3 -c "import re,sys; print(re.sub(r'[^A-Za-z0-9]','-',sys.argv[1]))" "$(readlink -f "$TEST_REPO")")"
_FIX_STORE="$HOME/.claude/projects/$_FIX_SLUG/memory"
if [ -d "$_FIX_STORE" ] && ! grep -ql "global_ref:" "$_FIX_STORE"/*.md 2>/dev/null; then
  echo "$TAG ⚠ fixture trigger-node mirror reclaimed (GC'd?) — regenerating the fixture (idempotent)." >&2
  python3 "$HERE/../fixtures/make_fixture.py" "$TEST_REPO" >/dev/null
fi

mkdir -p "$REPORTS" 2>/dev/null

# v0.1.7/B8: fixed names in a world-writable /tmp (not $TMPDIR-portable, and a predictable shared
# path is a collision/symlink-clobber footgun on a multi-user host) — mktemp + a trap so every exit
# path (including the early `exit 0`s above/below) cleans up.
DBT_CANARY_TMP="$(mktemp)"
DBT_DETAIL_TMP="$(mktemp)"
trap 'rm -f "$DBT_CANARY_TMP" "$DBT_DETAIL_TMP"' EXIT

# v0.1.7/B6: the 4th field is the comma-joined FAIL ids (additive — CSUM's tab-split callers below
# still read fields 1-3 positionally; unaffected). This is what lets the self-test move from a COUNT
# (`≥2 FAIL` — provably spurious-FAIL-able, the exact 2026-06-22 false-green incident) to an IDENTITY
# check (the SPECIFIC known defects, not just "something failed twice").
run_oracle() {
  python3 "$SCRIPTS/beta_checks.py" --repo "$TEST_REPO" --skill "$1" --json 2>/dev/null | python3 -c "
import sys,json
try:
    d=json.load(sys.stdin); s=d['summary']
    fail_ids=','.join(r['id'] for r in d['results'] if r['status']=='FAIL')
    print(f\"{s['fail']}\t{s['warn']}\t{s['pass']}\t{fail_ids}\")
    for r in d['results']:
        if r['status']=='FAIL': sys.stderr.write(f\"  FAIL {r['id']} ({r.get('defect_ref','')}) — {r.get('title','')}\n\")
        elif r['status']=='WARN': sys.stderr.write(f\"  warn {r['id']} ({r.get('defect_ref','')})\n\")
except Exception as e:
    print('ERR'); sys.stderr.write(f'  oracle parse error: {e}\n')
" 2>"$2"
}

# ── SELF-TEST: the oracle must still detect the frozen known-bad — by DEFECT IDENTITY, not count. ──
DBT_EXPECTED_IDS="CHK-GATE-BACKFILL,CHK-EVICT-STAGE"   # the real D3/D4 canary identities (beta_checks.py)
if [ -d "$CANARY" ]; then
  CSUM="$(run_oracle "$CANARY" "$DBT_CANARY_TMP")"
  CFAIL="$(printf '%s' "$CSUM" | cut -f1)"
  CIDS="$(printf '%s' "$CSUM" | cut -f4)"
  # subset check: every expected id must appear in the comma-joined CIDS list (substring match on a
  # comma-delimited set is safe here — the ids are a fixed, non-overlapping, hyphenated vocabulary).
  IDS_OK=1
  IFS=','; for _want in $DBT_EXPECTED_IDS; do
    case ",$CIDS," in *",$_want,"*) ;; *) IDS_OK=0 ;; esac
  done; unset IFS
  if [ "$IDS_OK" -ne 1 ]; then
    echo "$TAG ⚠⚠ SELF-TEST FAILED — the oracle no longer detects the frozen canary by IDENTITY (expected {$DBT_EXPECTED_IDS} ⊆ FAIL ids, got '$CIDS')." >&2
    echo "$TAG DETECTION is BROKEN; verdicts UNTRUSTWORTHY. Push ALLOWED (fail-open) — fix scripts/beta_checks.py." >&2
    : | python3 "$SCRIPTS/emit_result.py" --version "$(ver)" --self-test-ok false --canary-fail "$CFAIL" --expected-ids "$DBT_EXPECTED_IDS" --detected-ids "$CIDS" --probe-ok false --probe-expected-ids "" --probe-detected-ids "" --probe-stamp-ok false --generated-at "$(now)" --out "$REPORTS/latest.json" >/dev/null 2>&1 || true
    printf '%s\tSELFTEST_BROKEN\tcanary_fail=%s\tids=%s\n' "$(now)" "$CFAIL" "$CIDS" >> "$REPORTS/.gate-log.tsv" 2>/dev/null
    exit 0
  fi
else
  CFAIL="no-canary"; CIDS=""
  # v0.1.7 Gate-2a follow-up: the self-test never RAN here — the contract must not claim
  # expected_ids ⊆ detected_ids was proven when detected_ids is necessarily empty (a real
  # contradiction the prior code shipped: self_test.ok:true alongside a visibly-false ids claim).
  # Clear the EMITTED expected-ids too, so an empty ⊆ empty reads as "nothing compared", not
  # "compared and passed" — emit_result.py's `meaning` field is conditioned on this being empty.
  DBT_EXPECTED_IDS=""
  echo "$TAG note: canary missing — self-test SKIPPED (re-run install-gate.sh to populate it)." >&2
fi

# ── MAIN: test the working-tree version + emit the deterministic contract. ──
VER="$(ver)"
LASTVER="$(grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' "$REPORTS/.gate-log.tsv" 2>/dev/null | tail -1)"
if [ -n "$LASTVER" ] && [ "v$VER" != "$LASTVER" ]; then
  echo "$TAG ℹ new version ($LASTVER → v$VER): the gate checks KNOWN-defect regressions only — run \`/dream-beta-test\` for the full lens pass to catch NOVEL classes." >&2
fi
echo "$TAG consolidate-memory v$VER  vs  fixture  (self-test ✓ detection live) …" >&2
# v0.1.8/A1: the cycle-probe leg rides the MAIN invocation ONLY (never run_oracle/the canary leg —
# the canary is old-skill and must keep its exact {CHK-GATE-BACKFILL, CHK-EVICT-STAGE} identity set).
PROBE_ARGS=()
if [ -f "$PROBE_FILE" ]; then
  PROBE_ARGS=(--cycle-probe "$PROBE_FILE")
else
  echo "$TAG ⚠ cycle probe missing — run $HERE/install-gate.sh to generate $PROBE_FILE (cycle-identity teeth UNPROVEN; verdicts UNTRUSTWORTHY — fail-open)." >&2
fi
FULL="$(python3 "$SCRIPTS/beta_checks.py" --repo "$TEST_REPO" --skill "$SKILL" --json "${PROBE_ARGS[@]}" 2>/dev/null)"
# Extract the partitioned probe block; an absent/malformed block → ok=false (fail toward distrust,
# per SPEC-A §4.5 — missing teeth must never read as clean).
PROBE_SUM="$(printf '%s' "$FULL" | python3 -c "
import sys,json
try:
    d=json.load(sys.stdin).get('cycle_probe')
    if not d: print('false\t\t\tfalse')
    else:
        print('true' if d.get('ok') else 'false', end='\t')
        print(','.join(d.get('expected_ids',[])), end='\t')
        print(','.join(d.get('detected_ids',[])), end='\t')
        print('true' if d.get('stamp_verified') else 'false')
except Exception: print('false\t\t\tfalse')
" 2>/dev/null)"
PROBE_OK="$(printf '%s' "$PROBE_SUM" | cut -f1)"
PEXP="$(printf '%s' "$PROBE_SUM" | cut -f2)"
PDET="$(printf '%s' "$PROBE_SUM" | cut -f3)"
PSTAMP="$(printf '%s' "$PROBE_SUM" | cut -f4)"
if [ "$PROBE_OK" != "true" ]; then
  echo "$TAG ⚠⚠ CYCLE-PROBE TEETH-LOSS — expected {$PEXP} ⊆ detected FAIL ids, got '$PDET' (stamp $PSTAMP)." >&2
  echo "$TAG DETECTION is BROKEN; verdicts UNTRUSTWORTHY. Push ALLOWED (fail-open) — fix scripts/beta_checks.py or regenerate the probe." >&2
fi
VERDICT="$(printf '%s' "$FULL" | python3 "$SCRIPTS/emit_result.py" --version "$VER" --self-test-ok true \
  --canary-fail "$CFAIL" --expected-ids "$DBT_EXPECTED_IDS" --detected-ids "$CIDS" \
  --probe-ok "$PROBE_OK" --probe-expected-ids "$PEXP" --probe-detected-ids "$PDET" --probe-stamp-ok "$PSTAMP" \
  --generated-at "$(now)" --out "$REPORTS/latest.json" 2>"$DBT_DETAIL_TMP")"
DETAIL="$(cat "$DBT_DETAIL_TMP" 2>/dev/null)"
SUM="$(printf '%s' "$FULL" | python3 -c "import sys,json
try:
    d=json.load(sys.stdin); s=d['summary']; print(f\"{s['fail']}\t{s['warn']}\t{s['pass']}\")
except Exception: print('ERR')" 2>/dev/null)"
printf '%s\tv%s\t%s\n' "$(now)" "$VER" "${SUM:-ERR}" >> "$REPORTS/.gate-log.tsv" 2>/dev/null

case "$VERDICT" in
  clean)
    echo "$TAG ✓ 0 FAIL — v$VER clean of known regressions ($(printf '%s' "$SUM" | cut -f2) advisory warn) · result → $REPORTS/latest.json" >&2
    printf '%s' "$DETAIL" | grep -i '^  warn' >&2 || true; exit 0 ;;
  regression)
    echo "$TAG ❌ regression in v$VER. PUSH BLOCKED · machine-actionable findings → $REPORTS/latest.json" >&2
    printf '%s' "$DETAIL" | grep -i '^  FAIL' >&2
    echo "$TAG orchestrator → read $REPORTS/latest.json (verdict=regression · actionable[]) · human → /dream-beta-test · override → git push --no-verify" >&2
    exit 1 ;;
  selftest_broken)
    # v0.1.8/A1: the cycle-probe/canary teeth-loss case IS a real verdict (written to latest.json),
    # not an "unknown" — the loud teeth-loss lines above say WHY; here just route the exit.
    echo "$TAG ⚠ verdict=selftest_broken — the HARNESS is broken (see latest.json). Push ALLOWED (fail-open); never ship on this run's clean-reading." >&2
    exit 0 ;;
  *)
    echo "$TAG ⚠ no verdict (verdict='${VERDICT:-none}') — gate SKIPPED (fail-open). Push allowed." >&2
    printf '%s' "$DETAIL" >&2; exit 0 ;;
esac
