#!/usr/bin/env bash
# MAINTAINER continuous-QA gate for the consolidate-memory "dream" skill.
#
# For the marketplace owner who DEVELOPS consolidate-memory. Installed as a pre-push hook by
# `install-gate.sh`, it runs the deterministic beta-oracle against the version being pushed (the
# repo's working tree) on a FROZEN fixture and BLOCKS (exit 1) on any confirmed FAIL. End users who
# merely INSTALL the plugin don't need this — they use the `/dream-beta-test` skill.
#
# SELF-TEST (watch-the-watcher): proves the oracle still detects a frozen known-bad before trusting
# an "allow". FAIL-OPEN on any harness malfunction. Override a block with `git push --no-verify`.
# Writes the deterministic orchestrator contract to $REPORTS/latest.json (see ../docs/CONTRACT.md).
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SCRIPTS="$(cd "$HERE/../scripts" && pwd)"                       # plugin-relative engine
STATE="${DREAM_BETA_STATE:-$HOME/.dream-beta-test}"            # stable maintainer state (fixture/canary/reports)
REPORTS="${DREAM_BETA_REPORTS:-$STATE/reports}"
TEST_REPO="$STATE/gate-repo"                                    # generated by install-gate.sh / make_fixture.py
CANARY="${DBT_GATE_CANARY:-$STATE/canary-v0.1.19/scripts}"     # frozen known-bad (install-gate.sh populates it)
# The consolidate-memory scripts being pushed = the working tree of the repo the hook fires in.
SKILL="${DBT_GATE_SKILL:-$(git rev-parse --show-toplevel 2>/dev/null)/plugins/consolidate-memory/scripts}"
TAG="[dream-beta-test gate]"
now() { date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo now; }
ver() { python3 -c "import json;print(json.load(open('$SKILL/../.claude-plugin/plugin.json'))['version'])" 2>/dev/null || echo "?"; }

# Setup / sanity — any miss → FAIL-OPEN (a beta-tester must not block work on its own gaps).
if [ ! -f "$SCRIPTS/beta_checks.py" ] || [ ! -f "$SKILL/memory_status.py" ]; then
  echo "$TAG engine or consolidate-memory scripts not found — gate SKIPPED (fail-open)." >&2; exit 0; fi
if [ ! -f "$TEST_REPO/README.md" ]; then
  echo "$TAG fixture not set up — run $HERE/install-gate.sh first. Gate SKIPPED (fail-open)." >&2; exit 0; fi

mkdir -p "$REPORTS" 2>/dev/null
run_oracle() {
  python3 "$SCRIPTS/beta_checks.py" --repo "$TEST_REPO" --skill "$1" --json 2>/dev/null | python3 -c "
import sys,json
try:
    d=json.load(sys.stdin); s=d['summary']
    print(f\"{s['fail']}\t{s['warn']}\t{s['pass']}\")
    for r in d['results']:
        if r['status']=='FAIL': sys.stderr.write(f\"  FAIL {r['id']} ({r.get('defect_ref','')}) — {r.get('title','')}\n\")
        elif r['status']=='WARN': sys.stderr.write(f\"  warn {r['id']} ({r.get('defect_ref','')})\n\")
except Exception as e:
    print('ERR'); sys.stderr.write(f'  oracle parse error: {e}\n')
" 2>"$2"
}

# ── SELF-TEST: the oracle must still detect the frozen known-bad (≥2 FAIL). ──
if [ -d "$CANARY" ]; then
  CSUM="$(run_oracle "$CANARY" /tmp/.dbt_canary)"; rm -f /tmp/.dbt_canary
  CFAIL="$(printf '%s' "$CSUM" | cut -f1)"
  if ! printf '%s' "$CFAIL" | grep -qE '^[0-9]+$' || [ "$CFAIL" -lt 2 ]; then
    echo "$TAG ⚠⚠ SELF-TEST FAILED — the oracle no longer detects the frozen canary (expected ≥2 FAIL, got '$CFAIL')." >&2
    echo "$TAG DETECTION is BROKEN; verdicts UNTRUSTWORTHY. Push ALLOWED (fail-open) — fix scripts/beta_checks.py." >&2
    : | python3 "$SCRIPTS/emit_result.py" --version "$(ver)" --self-test-ok false --canary-fail "$CFAIL" --generated-at "$(now)" --out "$REPORTS/latest.json" >/dev/null 2>&1 || true
    printf '%s\tSELFTEST_BROKEN\tcanary_fail=%s\n' "$(now)" "$CFAIL" >> "$REPORTS/.gate-log.tsv" 2>/dev/null
    exit 0
  fi
else
  CFAIL="no-canary"
  echo "$TAG note: canary missing — self-test SKIPPED (re-run install-gate.sh to populate it)." >&2
fi

# ── MAIN: test the working-tree version + emit the deterministic contract. ──
VER="$(ver)"
LASTVER="$(grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' "$REPORTS/.gate-log.tsv" 2>/dev/null | tail -1)"
if [ -n "$LASTVER" ] && [ "v$VER" != "$LASTVER" ]; then
  echo "$TAG ℹ new version ($LASTVER → v$VER): the gate checks KNOWN-defect regressions only — run \`/dream-beta-test\` for the full lens pass to catch NOVEL classes." >&2
fi
echo "$TAG consolidate-memory v$VER  vs  fixture  (self-test ✓ detection live) …" >&2
FULL="$(python3 "$SCRIPTS/beta_checks.py" --repo "$TEST_REPO" --skill "$SKILL" --json 2>/dev/null)"
VERDICT="$(printf '%s' "$FULL" | python3 "$SCRIPTS/emit_result.py" --version "$VER" --self-test-ok true \
  --canary-fail "$CFAIL" --generated-at "$(now)" --out "$REPORTS/latest.json" 2>/tmp/.dbt_detail)"
DETAIL="$(cat /tmp/.dbt_detail 2>/dev/null)"; rm -f /tmp/.dbt_detail
SUM="$(printf '%s' "$FULL" | python3 -c "import sys,json
try:
    d=json.load(sys.stdin); s=d['summary']; print(f\"{s['fail']}\t{s['warn']}\t{s['pass']}\")
except Exception: print('ERR')" 2>/dev/null)"
printf '%s\tv%s\t%s\n' "$(now)" "$VER" "${SUM:-ERR}" >> "$REPORTS/.gate-log.tsv" 2>/dev/null

case "$VERDICT" in
  clean)
    echo "$TAG ✓ 0 FAIL — v$VER clean of known regressions ($(printf '%s' "$SUM" | cut -f2) advisory warn) · result → $REPORTS/latest.json" >&2
    printf '%s' "$DETAIL" | grep -i '^  warn' >&2 || true; exit 0 ;;
  regression)
    echo "$TAG ❌ regression in v$VER. PUSH BLOCKED · machine-actionable findings → $REPORTS/latest.json" >&2
    printf '%s' "$DETAIL" | grep -i '^  FAIL' >&2
    echo "$TAG orchestrator → read $REPORTS/latest.json (verdict=regression · actionable[]) · human → /dream-beta-test · override → git push --no-verify" >&2
    exit 1 ;;
  *)
    echo "$TAG ⚠ no verdict (verdict='${VERDICT:-none}') — gate SKIPPED (fail-open). Push allowed." >&2
    printf '%s' "$DETAIL" >&2; exit 0 ;;
esac
